[build]
  command = "npm run build"
  publish = "out"  # ou ".next/static" se for Next.js puro, mas o ideal é "out" com `next export`

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"