[build]
  command = "npm run build"
  publish = "out"   # Ajuste conforme seu build (Next.js static export usa 'out')

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"